### ISSUE TITLE
about the means of some codes

### ISSUE THREAD

**Issue by myhappycity** [rtaori/Black-Box-Audio#12]
hello,i can't understand  the means of some codes:
        self.input_audio = load_wav(input_wave_file).astype(np.float32)
        self.pop = np.expand_dims(self.input_audio, axis=0)
        self.pop = np.tile(self.pop, (self.pop_size, 1))
 What is the purpose of converting wave file into float，and also,you use genetic algorithm, In this algorithm, what exactly does population mean? Is it noise?
 Thank you very much!

**Comment by rtaori** [comment]
Hi @hohaiyth ,
The conversion into float is so that input types match (DeepSpeech expects the input audio as a float array).
The population in the genetic algorithm is a set of candidate samples that are refined every iteration. Noise is added at the end of each iteration to encourage diversity in the samples. For a more in-depth explanation, you can read Section 2 [in our paper](https://arxiv.org/pdf/1805.07820.pdf).

**Comment by rtaori** [comment]
Closing as there as been no further followup
