### ISSUE TITLE
ModuleNotFoundError: No module named 'util'

### ISSUE THREAD

**Issue by xinghua-qu** [rtaori/Black-Box-Audio#17]
For some reason, I met the error below. 
`from util.audio import audiofile_to_input_vector
ModuleNotFoundError: No module named 'util'`
Where is the util for importing? I did not find it

**Comment by StephenC808** [comment]
@QuXinghuaNTU I got the same error but I cant remember exactly how I got past it. I am not by my desktop at the moment but I believe I fixed it by using 'pip3 install -r reqirements.txt' instead of 'pip install -r reqirements.txt' in a new virtual environment. It was either that or a change in the version of pandas or matplotlib. Run pip3 freeze and compare the output to my output in issue #15

**Comment by rtaori** [comment]
Hi @QuXinghuaNTU,

Did you clone the right version of DeepSpeech (following instructions in the README)? The util comes from the DeepSpeech repo.

**Comment by suyufan** [comment]
> For some reason, I met the error below.
> `from util.audio import audiofile_to_input_vector ModuleNotFoundError: No module named 'util'`
> Where is the util for importing? I did not find it

You should to clone DeepSpeech.
`git clone -b 'v0.1.1' --single-branch --depth 1 https://github.com/mozilla/DeepSpeech.git`
